import 'package:flutter/material.dart';

import '../../sample_data.dart';
import '../../state/lead_store.dart';

class QuestsPage extends StatefulWidget {
  const QuestsPage({super.key});

  @override
  State<QuestsPage> createState() => _QuestsPageState();
}

class _QuestsPageState extends State<QuestsPage> {
  bool _showOpenOnly = true;

  List<QuestRecord> _visibleQuests(List<QuestRecord> quests) {
    if (_showOpenOnly) {
      return quests.where((q) => !q.completed).toList();
    }
    return quests;
  }

  void _addQuickQuest() {
    final stamp = DateTime.now().millisecondsSinceEpoch;
    LeadStore.instance.addQuest(
      QuestRecord(
        title: 'Door Knock Sprint #${stamp % 1000}',
        status: 'Planned',
        details: 'Autogenerated field quest for immediate follow-up routing.',
      ),
    );
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Quick quest added.')),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
              child: Column(
                children: [
                  Row(
                    children: [
                      IconButton(
                        onPressed: () => Navigator.pop(context),
                        icon: const Icon(Icons.arrow_back),
                      ),
                      const Expanded(
                        child: Text(
                          'Quests',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 22,
                            fontWeight: FontWeight.w700,
                            color: Color(0xFF233655),
                          ),
                        ),
                      ),
                      const SizedBox(width: 48),
                    ],
                  ),
                  const SizedBox(height: 8),
                  Row(
                    children: [
                      Expanded(
                        child: SegmentedButton<bool>(
                          segments: const [
                            ButtonSegment<bool>(value: true, label: Text('Open')),
                            ButtonSegment<bool>(value: false, label: Text('All')),
                          ],
                          selected: {_showOpenOnly},
                          onSelectionChanged: (selection) {
                            setState(() {
                              _showOpenOnly = selection.first;
                            });
                          },
                        ),
                      ),
                      const SizedBox(width: 8),
                      ElevatedButton(
                        onPressed: _addQuickQuest,
                        child: const Text('Quick Add'),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            Expanded(
              child: ValueListenableBuilder<List<QuestRecord>>(
                valueListenable: LeadStore.instance.questsNotifier,
                builder: (context, quests, _) {
                  final visible = _visibleQuests(quests);
                  if (visible.isEmpty) {
                    return const Center(
                      child: Text('No quests found for this filter.'),
                    );
                  }

                  return ListView.builder(
                    padding: const EdgeInsets.all(16),
                    itemCount: visible.length,
                    itemBuilder: (context, index) {
                      final quest = visible[index];
                      final sourceIndex = quests.indexOf(quest);
                      return _QuestTile(
                        title: quest.title,
                        status: quest.status,
                        details: quest.details,
                        completed: quest.completed,
                        onComplete: quest.completed
                            ? null
                            : () => LeadStore.instance.markQuestCompleted(sourceIndex),
                      );
                    },
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _QuestTile extends StatelessWidget {
  const _QuestTile({
    required this.title,
    required this.status,
    required this.details,
    required this.completed,
    required this.onComplete,
  });

  final String title;
  final String status;
  final String details;
  final bool completed;
  final VoidCallback? onComplete;

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: ListTile(
        title: Text(title),
        subtitle: Text(details),
        trailing: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Chip(label: Text(status)),
            const SizedBox(width: 8),
            TextButton(
              onPressed: onComplete,
              child: Text(completed ? 'Done' : 'Complete'),
            ),
          ],
        ),
      ),
    );
  }
}
