import 'package:flutter/material.dart';

import '../../sample_data.dart';
import '../../state/lead_store.dart';

class QuestsPage extends StatefulWidget {
  const QuestsPage({super.key});

  @override
  State<QuestsPage> createState() => _QuestsPageState();
}

class _QuestsPageState extends State<QuestsPage> {
  bool _showOpenOnly = true;

  List<QuestRecord> _visibleQuests(List<QuestRecord> quests) {
    if (_showOpenOnly) {
      return quests.where((q) => !q.completed).toList();
    }
    return quests;
  }

  void _addQuickQuest() {
    final stamp = DateTime.now().millisecondsSinceEpoch;
    LeadStore.instance.addQuest(
      QuestRecord(
        title: 'Door Knock Sprint #${stamp % 1000}',
        status: 'Planned',
        details: 'Autogenerated field quest for immediate follow-up routing.',
      ),
    );
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Quick quest added.')),
    );
  }

  Future<void> _editQuest(int index, QuestRecord quest) async {
    final titleController = TextEditingController(text: quest.title);
    final detailsController = TextEditingController(text: quest.details);
    final statusController = TextEditingController(text: quest.status);

    final didSave = await showDialog<bool>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Edit Quest'),
          content: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                TextField(
                  controller: titleController,
                  decoration: const InputDecoration(labelText: 'Title'),
                ),
                const SizedBox(height: 10),
                TextField(
                  controller: statusController,
                  decoration: const InputDecoration(labelText: 'Status'),
                ),
                const SizedBox(height: 10),
                TextField(
                  controller: detailsController,
                  minLines: 2,
                  maxLines: 4,
                  decoration: const InputDecoration(labelText: 'Details'),
                ),
              ],
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context, false),
              child: const Text('Cancel'),
            ),
            ElevatedButton(
              onPressed: () => Navigator.pop(context, true),
              child: const Text('Save'),
            ),
          ],
        );
      },
    );

    if (didSave != true) {
      titleController.dispose();
      detailsController.dispose();
      statusController.dispose();
      return;
    }

    final nextTitle = titleController.text.trim();
    final nextStatus = statusController.text.trim();
    final nextDetails = detailsController.text.trim();

    titleController.dispose();
    detailsController.dispose();
    statusController.dispose();

    final updated = quest.copyWith(
      title: nextTitle.isEmpty ? quest.title : nextTitle,
      status: nextStatus.isEmpty ? quest.status : nextStatus,
      details: nextDetails.isEmpty ? quest.details : nextDetails,
    );

    LeadStore.instance.updateQuest(index, updated);
    if (!mounted) {
      return;
    }
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Quest updated.')),
    );
  }

  Future<void> _deleteQuest(int index) async {
    final confirm = await showDialog<bool>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Delete Quest?'),
          content: const Text('This action cannot be undone.'),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context, false),
              child: const Text('Cancel'),
            ),
            ElevatedButton(
              onPressed: () => Navigator.pop(context, true),
              child: const Text('Delete'),
            ),
          ],
        );
      },
    );

    if (confirm != true) {
      return;
    }

    LeadStore.instance.deleteQuest(index);
    if (!mounted) {
      return;
    }
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Quest deleted.')),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).scaffoldBackgroundColor,
      body: SafeArea(
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
              child: Column(
                children: [
                  Row(
                    children: [
                      IconButton(
                        onPressed: () => Navigator.pop(context),
                        icon: const Icon(Icons.arrow_back),
                      ),
                      Expanded(
                        child: Text(
                          'Quests',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 22,
                            fontWeight: FontWeight.w700,
                            color: Theme.of(context).colorScheme.onSurface,
                          ),
                        ),
                      ),
                      const SizedBox(width: 48),
                    ],
                  ),
                  const SizedBox(height: 8),
                  Row(
                    children: [
                      Expanded(
                        child: SegmentedButton<bool>(
                          segments: const [
                            ButtonSegment<bool>(value: true, label: Text('Open')),
                            ButtonSegment<bool>(value: false, label: Text('All')),
                          ],
                          selected: {_showOpenOnly},
                          onSelectionChanged: (selection) {
                            setState(() {
                              _showOpenOnly = selection.first;
                            });
                          },
                        ),
                      ),
                      const SizedBox(width: 8),
                      ElevatedButton(
                        onPressed: _addQuickQuest,
                        child: const Text('Quick Add'),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            Expanded(
              child: ValueListenableBuilder<List<QuestRecord>>(
                valueListenable: LeadStore.instance.questsNotifier,
                builder: (context, quests, _) {
                  final visible = _visibleQuests(quests);
                  if (visible.isEmpty) {
                    return Center(
                      child: Text(
                        'No quests found for this filter.',
                        style: TextStyle(color: Theme.of(context).textTheme.bodySmall?.color),
                      ),
                    );
                  }

                  return ListView.builder(
                    padding: const EdgeInsets.all(16),
                    itemCount: visible.length,
                    itemBuilder: (context, index) {
                      final quest = visible[index];
                      final sourceIndex = quests.indexOf(quest);
                      return _QuestTile(
                        title: quest.title,
                        status: quest.status,
                        details: quest.details,
                        completed: quest.completed,
                        onEdit: () => _editQuest(sourceIndex, quest),
                        onDelete: () => _deleteQuest(sourceIndex),
                        onComplete: quest.completed
                            ? null
                            : () => LeadStore.instance.markQuestCompleted(sourceIndex),
                      );
                    },
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _QuestTile extends StatelessWidget {
  const _QuestTile({
    required this.title,
    required this.status,
    required this.details,
    required this.completed,
    required this.onEdit,
    required this.onDelete,
    required this.onComplete,
  });

  final String title;
  final String status;
  final String details;
  final bool completed;
  final VoidCallback onEdit;
  final VoidCallback onDelete;
  final VoidCallback? onComplete;

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              title,
              style: TextStyle(
                fontWeight: FontWeight.w700,
                color: Theme.of(context).colorScheme.onSurface,
              ),
            ),
            const SizedBox(height: 6),
            Text(details),
            const SizedBox(height: 10),
            Row(
              children: [
                Chip(label: Text(status)),
                const SizedBox(width: 8),
                TextButton(
                  onPressed: onComplete,
                  child: Text(completed ? 'Done' : 'Complete'),
                ),
              ],
            ),
            Row(
              children: [
                TextButton.icon(
                  onPressed: onEdit,
                  icon: Icon(Icons.edit_outlined, size: 18, color: Theme.of(context).colorScheme.primary),
                  label: Text('Edit', style: TextStyle(color: Theme.of(context).colorScheme.primary)),
                ),
                const SizedBox(width: 8),
                TextButton.icon(
                  onPressed: onDelete,
                  icon: Icon(Icons.delete_outline, size: 18, color: Theme.of(context).colorScheme.error),
                  label: Text('Delete', style: TextStyle(color: Theme.of(context).colorScheme.error)),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
